#  #command: elasticsearch -Des.network.host=0.0.0.0

gg-nginx:
  image: ry:nginx1.9
  ports:
    - "80:80"
    - "443:443"
  links:
    - gg-php56:phpfpm
  volumes:
    - /data/nginx/conf:/etc/nginx
    - /data/nginx:/data/nginx
gg-redis:
  image: redis:latest
  volumes:
    - /data/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    - /data/redis/data:/data
  ports:
    - "192.168.0.1:6379:6379"
  #command: "redis-server /usr/local/etc/redis/redis.conf" 

gg-mongodb26:
  image: mongo:2.6.11
  volumes:
    - /data/mongodb/logs:/data/mongodb/logs
    - /data/mongodb/data:/data/db
  ports:
    - "192.168.0.1:27017:27017"

gg-php56:
  image: ry:php56

  links:
    - gg-mysql:mysql
    - gg-mongodb26:mongodb
    - gg-redis:redis
  volumes:
    - /data/php/conf/php.ini:/etc/php.ini
    - /data/nginx/data:/data/nginx/data
  command: "php-fpm -c /etc/php.ini"


gg-mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=snowmysql1#iot2012
  ports:
    - "192.168.0.1:3306:3306"
  volumes:
    - /data/mysql/data:/var/lib/mysql
    - /data/mysql/conf/conf.d:/etc/mysql/conf.d

gg-html2png:
  image: ry:html2png
  links:
    - gg-redis:redis
  environment:
    - GG_REDIS_HOST=redis
  command: "php  /html2png/gogoinfo/server/html2png.php"
  volumes:
    - /data/nginx/data:/html2png
    #- /data/php/conf/html2png.ini:/etc/php.ini
