#/bin/bash 
mysql=http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.20.tar.gz
libunwind=http://download.savannah.gnu.org/releases/libunwind/libunwind-1.1.tar.gz
gperftools=https://gperftools.googlecode.com/files/gperftools-2.1.zip
mongodb=http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-2.6.3.tgz
php=http://jp1.php.net/distributions/php-5.5.15.tar.bz2
geoipclib=http://geolite.maxmind.com/download/geoip/api/c/GeoIP.tar.gz
tenginx=http://tengine.taobao.org/download/tengine-2.0.3.tar.gz
geoCityLib=http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
geoIp=http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
pcre=http://downloads.sourceforge.net/project/pcre/pcre/8.21/pcre-8.21.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fpcre%2Ffiles%2Fpcre%2F8.21%2F&ts=1407240651&use_mirror=nchc
xdebug=http://xdebug.org/files/xdebug-2.2.3.tgz
phpRedis=https://github.com/nicolasff/phpredis/archive/master.zip
phpMongo=https://codeload.github.com/mongodb/mongo-php-driver/zip/master
#for centos 6.4+ x64 only 1.0.16 can be compiled successfully
libmemcached=https://launchpad.net/libmemcached/1.0/1.0.16/+download/libmemcached-1.0.17.tar.gz
igbinary=http://pecl.php.net/get/igbinary-1.1.1.tgz
phpMemcached=http://pecl.php.net/get/memcached-2.1.0.tgz
yaf=http://pecl.php.net/get/yaf
snmp=http://nchc.dl.sourceforge.net/project/net-snmp/net-snmp/5.7.2/net-snmp-5.7.2.tar.gz
aspell=ftp://ftp.gnu.org/gnu/aspell/aspell-0.60.6.1.tar.gz
libmcryptDev=http://pkgs.repoforge.org/libmcrypt/libmcrypt-devel-2.5.7-1.2.el6.rf.x86_64.rpm
libmcrypt=http://pkgs.repoforge.org/libmcrypt/libmcrypt-2.5.7-1.2.el6.rf.x86_64.rpm
node=http://nodejs.org/dist/node-latest.tar.gz
redis=http://download.redis.io/releases/redis-2.6.15.tar.gz
memcached=http://memcached.org/files/memcached-1.4.20.tar.gz